Lets begin with importing numpy as np.

In [1]:
import numpy as np

Numpy is a package that is essential, it runs very fast and good. Of course one can use python without numpy to do mathematical operation and likewise but numpy is very optimized.

The building part of numpy is (surprisingly not) arrays, or stack of arrays i.e matrix/tensors etc. Let's start with creating a numpy array.

In [26]:
a = np.array([1,2,3])
print("a = {}".format(a))

b = np.array((1,2,3))
print("b = {}".format(b))

print("The shape of the array is {}".format(a.shape))
print("The datatype of the element in a is {}".format(a.dtype)+ '\n')

c = np.array([1.4, 6, np.pi])
print("c = {}".format(c))
print("The datatype of the element in c is {}".format(c.dtype)+ '\n')

print("The output of np.arrays is {}".format(type(c)))

a = [1 2 3]
b = [1 2 3]
The shape of the array is (3,)
The datatype of the element in a is int32

c = [1.4        6.         3.14159265]
The datatype of the element in c is float64

The output of np.arrays is <class 'numpy.ndarray'>


In [29]:
A = np.array([[1,1,1],[2,2,2]])
print("A = {}".format(A))

print("The shape of the matrix is {}".format(A.shape))
print("The datatype of the element in A is {}".format(A.dtype)+ '\n')

print("The output of np.arrays is {}".format(type(A)))

A = [[1 1 1]
 [2 2 2]]
The shape of the matrix is (2, 3)
The datatype of the element in A is int32

The output of np.arrays is <class 'numpy.ndarray'>


We saw that we can initialize a numpy array from python list. There are many ways to initialize numpy arrays, depending on the usage. Let's see some of the more common standard array initialization.   

In [38]:
A = np.empty(shape=(3,3))
B = np.empty(shape=(3,3),dtype=np.int8)

print(A)
print(B)

print("Empty returns a ndarray of given shape. One should be careful of initialize this way if one care about the elements that is initialized" + '\n')

C = np.identity(5)
print(C)

D = np.ones(shape=(5,5))
E = np.zeros(shape=(4,2))

F = np.full_like(E,5)

print(D)
print(E)
print(F)

print(np.linspace(start=0,stop=5))

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.89318163e-321]
 [9.18824177e-312 9.18824177e-312 0.00000000e+000]]
[[0 0 0]
 [0 0 1]
 [1 1 0]]
Empty returns a ndarray of given shape. One should be careful of initialize this way if one care about the elements that is initialized

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]]
[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  

The array operation is like python operation. Some is in-place some are not.

In [46]:
a = np.array([1,2,3])
b = np.array([2,2,2])

print(a + b*0.5)

A = np.ones(shape=(2,3))
B = np.array([[1,2,3],[1,2,3]])
C = A + B
print(C)

print(C[1])
print(C[:,0])
print(C[0,0])

[2. 3. 4.]
[[2. 3. 4.]
 [2. 3. 4.]]
[2. 3. 4.]
[2. 2.]
2.0


The ndarry also have some nice operation

In [53]:
B = np.array([[1,2,3],[1,2,3]])
print(B.sum())
print(B.mean())

print(B.sum(axis=1))
print(B.sum(axis=0))

12
2.0
[6 6]
[2 4 6]


One of the most useful thing is to update the array, either reshaping it, add an axis or append something.