Numpy has additional submodules that is useful for mathematical programming. The first one to introduce is linear algebra.

In [1]:
import numpy as np
import numpy.linalg as linalg

In [2]:
#Let's try to multiply 2 matrices
A = np.ones(shape=(3,2))
b = np.ones(shape=(2,1))*2

print(A)
print(b)
print(A * b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2.]
 [2.]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

We saw that when multiplying 2 vectors/matrices, numpy try to to elementwise multiplication and/or broadcast the matrices. To be able to the matrix multiplication we need to use matmul or @-operator

In [6]:
#Let's try again but use the real multiplication
A = np.ones(shape=(3,2))
b = np.ones(shape=(2,1))*2

y = np.matmul(A,b)
print(y)

y = A @ b
print(y)

[[4.]
 [4.]
 [4.]]
[[4.]
 [4.]
 [4.]]


In [12]:
#Create a pseudorandom matrix
C = np.array([[2,6,3],[12, 24 ,-5 ],[0,23,10]])

#QR decompistion, get a traiangel and orthogonal matrix 
q,r = linalg.qr(C)

print(q)
print(r)


[[-0.16439899  0.08429682 -0.98278534]
 [-0.98639392 -0.01404947  0.16379756]
 [-0.          0.99634164  0.08545959]]
[[-12.16552506 -24.6598481    4.43877266]
 [  0.          23.0844513   10.2865542 ]
 [  0.           0.          -2.91274785]]


QR, is a stable way to get a orthogonal matrix. The mode is ‘reduced’ i.e for not square matrices the "zero-padding" does not exist, if one want the original dimension one can change the mode.

In [13]:
#Create a invertible matrix
C = np.array([[2,6,3],[12, 24 ,-5 ],[0,23,10]])
w,v = linalg.eig(C)

print(w)
print(v)

[ 3.41035466 21.36073766 11.22890767]
[[ 0.65770486  0.26620951  0.33812794]
 [-0.20747096  0.42688462  0.05021208]
 [ 0.72414096  0.86423493  0.93975967]]


In [19]:
#Solve a linear system without wasting computation time with inverting matrix 
C = np.array([[2,6,3],[12, 24 ,-5 ],[0,23,10]])
A = np.ones(shape=(3,2))
b = np.ones(shape=(2,1))*2
y = A @ b


x = linalg.solve(C,y)
print(x)

[[ 1.28117359]
 [-0.26405868]
 [ 1.00733496]]


We can inverse the matrix to calculate the Ax=b but it's is inefficient. Thus solve is often used.

We will see that scipy is often also used, it also have some of the nice method that numpy.linalg / numpy modules has.
If the user don't have scipy installed numpy.dual can help speed up to process such as cholesky, det,eig and such.

Another important method is fft i.e dfft 

In [26]:
#Create an array and matrix
C = np.array([[2,6,3],[12, 24 ,-5 ],[0,23,10]])
y = np.array([1,2,3])

#We can fourier and also inverse fourier and get back our array albiet as complex now
print(np.fft.fft(y))
print(np.fft.ifft(np.fft.fft(y)))

#We can do it row wise
print(np.fft.fftn(C))


[ 6. +0.j        -1.5+0.8660254j -1.5-0.8660254j]
[1.+0.j 2.+0.j 3.+0.j]
[[ 75.  +0.j         -16.5-38.97114317j -16.5+38.97114317j]
 [-21.  +1.73205081j  -7.5 -0.8660254j   16.5-32.04293994j]
 [-21.  -1.73205081j  16.5+32.04293994j  -7.5 +0.8660254j ]]
[ 6. +0.j        -1.5+0.8660254j]


If one has real data, one can either abs or do Hermitian fft (if possible)

We can also with numpy use functional programming, for some more common operation. 

apply_along_axis(func1d, axis, arr, \*args, …) - Apply a function to 1-D slices along the given axis.

apply_over_axes(func, a, axes) - Apply a function repeatedly over multiple axes.

vectorize(pyfunc[, otypes, doc, excluded, …]) - Generalized function class.

frompyfunc(func, nin, nout, *[, identity]) - Takes an arbitrary Python function and returns a NumPy ufunc.

piecewise(x, condlist, funclist, \*args, \*\*kw) - Evaluate a piecewise-defined function.

In [27]:
#Unsorted array
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
np.apply_along_axis(sorted, 1, b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

The numpy library also has some statistic, such as order statistics, averages, variances, covariance and histograms

In [28]:
#Pretend real data
a = np.array([[10, 7, 4], [3, 2, 1]])
print(np.percentile(a, 50, axis=0))
print(np.percentile(a, 50, axis=1))

[6.5 4.5 2.5]
[7. 2.]
