In [1]:
import numpy as np

Numpy has sort algorithm just as python inbuild sort algorithms. Numpys' sort is good and fast and uses quicksort algorithm, but mergesort and heapsort are also available. For most applications, the default quicksort is more than sufficient.

In [3]:
x = np.array([2, 1, 4, 3, 5])
print(np.sort(x))

[1 2 3 4 5]


In [7]:
x = np.array([2, 1, 4, 3, 5])
x.sort()
print(x)

[1 2 3 4 5]


In-Place sort also work. Argsort also works, which returns the indices of the sorted elements.

In [10]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)
print(x)
print(x[i])

[1 0 3 2 4]
[2 1 4 3 5]
[1 2 3 4 5]


We can also sort along rows/columns

In [22]:
x = np.linspace(start=12,stop=0)
x = x.reshape((10,-1))
print(x)
print(np.sort(x, axis=0))
print(np.sort(x, axis=1))

[[12.         11.75510204 11.51020408 11.26530612 11.02040816]
 [10.7755102  10.53061224 10.28571429 10.04081633  9.79591837]
 [ 9.55102041  9.30612245  9.06122449  8.81632653  8.57142857]
 [ 8.32653061  8.08163265  7.83673469  7.59183673  7.34693878]
 [ 7.10204082  6.85714286  6.6122449   6.36734694  6.12244898]
 [ 5.87755102  5.63265306  5.3877551   5.14285714  4.89795918]
 [ 4.65306122  4.40816327  4.16326531  3.91836735  3.67346939]
 [ 3.42857143  3.18367347  2.93877551  2.69387755  2.44897959]
 [ 2.20408163  1.95918367  1.71428571  1.46938776  1.2244898 ]
 [ 0.97959184  0.73469388  0.48979592  0.24489796  0.        ]]
[[ 0.97959184  0.73469388  0.48979592  0.24489796  0.        ]
 [ 2.20408163  1.95918367  1.71428571  1.46938776  1.2244898 ]
 [ 3.42857143  3.18367347  2.93877551  2.69387755  2.44897959]
 [ 4.65306122  4.40816327  4.16326531  3.91836735  3.67346939]
 [ 5.87755102  5.63265306  5.3877551   5.14285714  4.89795918]
 [ 7.10204082  6.85714286  6.6122449   6.36734694  6.1

What if we don't want to sort the whole array but still want the smallest number at the start. Let me introduce you to partition. It takes an array and a number K and part the array with the smallest K:th element to the left and the other to the right in a arbitrary order.

In [26]:
x = np.array([7, 2, 1, 6, 3, 5, 4])
print(np.partition(x, 3))

x = np.array([7, 2, 3, 1, 6, 5, 4])
print(np.partition(x, 3))

[2 1 3 4 5 6 7]
[2 1 3 4 6 5 7]


We have looked at arrays and Matrices/tensors/ndarry that is of the same dtype. In some application one want to have a ndarry with some structured data. 

In [27]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [29]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')}) #U10 = Unicode with length < 10, #i4 = integer 4-byte, #f8 = float 8-byte
print(data)

[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]


In [30]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


We can now get data as we usually do and do boolean operation.

In [31]:
print(data[0])
print(data[1]['name'])
print(data[data['age'] < 30]['name'])

('Alice', 25, 55.)
Bob
['Alice' 'Doug']


The structured data will soon be obsolete but is a nice introduction to Pandas 