Numpy is very good, since it help us with faster and smaller code. 

Python is "written" in C where one can see x = 7 as struct _int{adress, value, ...}, we want to use the simple python code while still being fast. For example see picture, a python list = [1,2,3,4,...] becomes a bit messy, when we add more data and use operation on it. But a numpy array solves this.    

![title](Pictures/array_vs_list.png)

Lets begin study numpy by importing numpy as np.

In [2]:
import numpy as np

Numpy is a package that is essential, it runs very fast and good. Of course one can use python without numpy to do mathematical operation and likewise but numpy is very optimized.

The building part of numpy is (surprisingly not) arrays, or stack of arrays i.e matrix/tensors etc. Let's start with creating a numpy array.

In [26]:
a = np.array([1,2,3])
print("a = {}".format(a))

b = np.array((1,2,3))
print("b = {}".format(b))

print("The shape of the array is {}".format(a.shape))
print("The datatype of the element in a is {}".format(a.dtype)+ '\n')

c = np.array([1.4, 6, np.pi])
print("c = {}".format(c))
print("The datatype of the element in c is {}".format(c.dtype)+ '\n')

print("The output of np.arrays is {}".format(type(c)))

a = [1 2 3]
b = [1 2 3]
The shape of the array is (3,)
The datatype of the element in a is int32

c = [1.4        6.         3.14159265]
The datatype of the element in c is float64

The output of np.arrays is <class 'numpy.ndarray'>


In [29]:
A = np.array([[1,1,1],[2,2,2]])
print("A = {}".format(A))

print("The shape of the matrix is {}".format(A.shape))
print("The datatype of the element in A is {}".format(A.dtype)+ '\n')

print("The output of np.arrays is {}".format(type(A)))

A = [[1 1 1]
 [2 2 2]]
The shape of the matrix is (2, 3)
The datatype of the element in A is int32

The output of np.arrays is <class 'numpy.ndarray'>


We saw that we can initialize a numpy array from python list. There are many ways to initialize numpy arrays, depending on the usage. Let's see some of the more common standard array initialization.   

In [38]:
A = np.empty(shape=(3,3))
B = np.empty(shape=(3,3),dtype=np.int8)

print(A)
print(B)

print("Empty returns a ndarray of given shape. One should be careful of initialize this way if one care about the elements that is initialized" + '\n')

C = np.identity(5)
print(C)

D = np.ones(shape=(5,5))
E = np.zeros(shape=(4,2))

F = np.full_like(E,5)

print(D)
print(E)
print(F)

print(np.linspace(start=0,stop=5))

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.89318163e-321]
 [9.18824177e-312 9.18824177e-312 0.00000000e+000]]
[[0 0 0]
 [0 0 1]
 [1 1 0]]
Empty returns a ndarray of given shape. One should be careful of initialize this way if one care about the elements that is initialized

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]]
[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  

The array operation is like python operation. Some is in-place some are not.

In [50]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


We can define the out from a function for some good memory usage and likewise.

Let's study some element-wise operation

In [46]:
a = np.array([1,2,3])
b = np.array([2,2,2])

print(a + b*0.5)

A = np.ones(shape=(2,3))
B = np.array([[1,2,3],[1,2,3]])
C = A + B
print(C)

print(C[1])
print(C[:,0])
print(C[0,0])

[2. 3. 4.]
[[2. 3. 4.]
 [2. 3. 4.]]
[2. 3. 4.]
[2. 2.]
2.0


We want to vectorize operations, which happens with above. Another means of vectorizing operations is to use NumPy's broadcasting functionality. Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes  

In [52]:
a = np.array([0, 1, 2])
b = np.array([1, 1, 1])
print(a + b)

[1 2 3]


In [53]:
a = np.array([0, 1, 2])
print(a + 1)

[1 2 3]


So when the array is of different shape the + operation behaves like [0,1,2] + [1,1,1] but instead of copy 1, 3 times the numpy calculate better with broadcasting. This gets "complicated" when adding dimension but broadcasting behaves similar. 

In [54]:
M = np.ones((3, 3))
print(M + a)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [55]:
a = np.array([0,1,2])
b = np.array([[0],[1],[2]])
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


![title](Pictures/broadcasting.png)

Basically the array "copies" accordingly to witch has the lowest dimension. If they both have same lowest dimension the one with shape equal to 1 in that dimension is stretched. This is a bit useful but can be thought as extra .

With the basic over we study some of the nice operation that ndarry has. Most operation is implemented and can be operated w.r.p different dimension and such.

In [53]:
B = np.array([[1,2,3],[1,2,3]])
print(B.sum())
print(B.mean())

print(B.sum(axis=1))
print(B.sum(axis=0))

12
2.0
[6 6]
[2 4 6]


One of the most useful thing is to update the array, either reshaping it, add an axis or append something.

In [5]:
a = np.arange(12)
print(a)

b = a.reshape(3, 4)
print(b)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
a[11:] = 0
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10  0]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10  0]]


the reshape function does not copy the data, it doesn't even own its data as seen.

In [9]:
b[1:2,0] = 0
print(a)
print(b)

[ 0  1  2  3  0  5  6  7  0  9 10  0]
[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 0  9 10  0]]


This can seen as bad but is very useful since we can use reshape as a good tool to just change "pointers" but still operate on the new shape. Numpy is built on C so C-contiguous is happening when initializing, so one should for better code, store as C.   

In [10]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[1,2,3]])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [1 2 3]]


In [15]:
a2 = np.concatenate((a,a),axis=0)
print(a2)
print(a)
try:
    a2 = np.concatenate((a,a),axis=1)
    print(a2)
except:
    print("axis 1 is out of bounds for array of dimension 1")
    print(a.shape)
    


[1 2 3 1 2 3]
[1 2 3]
axis 1 is out of bounds for array of dimension 1
(3,)


In [20]:
try:
    ab = np.concatenate([a,b],axis=0)
    print(ab)
except:
    print("axis 1 is out of bounds for array of dimension 1")
ab = np.concatenate([a,b],axis=None)
print(ab)

axis 1 is out of bounds for array of dimension 1
[1 2 3 1 2 3 1 2 3]


We saw that when concatenate we need to have the same dimension. If we want to append, we can use axis = None as a flatten method. 

In [34]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3],[1,2,3]])
print(a)
print(b)
ab = np.concatenate((a,b),axis=0)
print(ab)
c = np.array([[1,2]])
ac = np.concatenate((b,c),axis=1)
print(ac)

[[1 2 3]]
[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly

It's a bit clumsy to use, so let's study different way to append/concatenate 

In [39]:
a = np.array([1,2,3])
b = np.array([1,2,3])

print("columne-wise stack")
ab = np.hstack((a,b))
print(ab)
print(ab.shape)

a = np.array([[1],[2],[3]])
b = np.array([[1],[2],[3]])
print(a)
ab = np.hstack((a,b))
print(ab)
print(ab.shape)

columne-wise stack
[1 2 3 1 2 3]
(6,)
[[1]
 [2]
 [3]]
[[1 1]
 [2 2]
 [3 3]]
(3, 2)


In [40]:
a = np.array([1,2,3])
b = np.array([1,2,3])

print("row-wise stack")
ab = np.vstack((a,b))
print(ab)
print(ab.shape)
a = np.array([[1],[2],[3]])
b = np.array([[1],[2],[3]])
print(a)
ab = np.vstack((a,b))
print(ab)
print(ab.shape)

columne-wise stack
[[1 2 3]
 [1 2 3]]
(2, 3)
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]
 [1]
 [2]
 [3]]
(6, 1)


This is a bit confusing, especially in higher dimension, but i like to think of column and row stacking. Sometime broadcasting happens so one need to think what happens. 

In [46]:
a = np.array([1,2,3])
b = np.array([1,2,3])

print("columns-wise deep stack i.e add a dimension")
ab = np.dstack((b,a))
print(ab)
print(ab.shape)

ab2 = np.dstack((ab,a))
print(ab2)
print(ab2.shape)

columns-wise deep stack i.e add a dimension
[[[1 1]
  [2 2]
  [3 3]]]
(1, 3, 2)
[[[1 1 1]
  [2 2 2]
  [3 3 3]]]
(1, 3, 3)


Similarly (-note to future self, stop overusing adverb-) splitting is almost the same but with split, vsplit, hsplic and dsplit  

MATLAB-feeling without MATLAB <3. One thing I like about matlab, beside the workspace, is the boolean operation on array. Luckily we can do that with numpy.

In [57]:
a = np.array([1,2,3])
b = [1,2,3]

print(a < 2)
print(b < 2)


[ True False False]


TypeError: '<' not supported between instances of 'list' and 'int'

We can use these boolean arrays as input

In [71]:
print(np.sum(a > 1))

print(np.sum(a > 1) & np.sum(a <= 2))
print(np.sum((a > 1) & (a <= 2)))
print(a[a > 1])

2
2
1
[2 3]
